services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mi-app-spring
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/perfulandia?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mipassword123
    restart: always
